before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

language: bash

sudo: required

services:
- docker

scripts:
- echo "build junglecloud02"